---
title: "math_motion_project"
output: html_document
date: '2023-11-16'
---

```{r setup, include=FALSE}
## DH: I don't think this is necessary unless you're knitting to slides
knitr::opts_chunk$set(echo = TRUE)

```

```{r}
## DH: `ggplot2` is included in `tidyverse`
library(ggplot2)
library(tidyverse)
library(plotly)

```

<!-- DH: What is this dataset?  Where did it come from?  Why are we looking at it?  What do we expect to see? -->

```{r}
## read and understand data ##
## DH: Don't use hard-coded absolute paths.  In this case, we don't need a path at all, since the file is in the same directory as the script.  Recommend using `here` when you have the project organized into folders. 
# tictoc::tic()
time.df <- read.csv('coordinates_Dami.csv')
# tictoc::toc()
## DH: FWIW, on larger files read_csv is significantly faster, 3.7 sec vs. 1.3 sec
# tictoc::tic()
# foo <- read_csv('coordinates_Dami.csv')
# tictoc::toc()
## DH: ???
head(df)


```

```{r}
## DH: This just tells us the class for each column. `skim` would be more useful here
#looking at the column's info
str(time.df)

```

<!-- DH: Anything notable here? -->

```{r}
#Convert hertz to second (1 second = 30 hertz) 
## DH: unnecessary pipe; save memory by doing this when you load the csv
time.df2 <- time.df %>%
    mutate(t_sec = X/30)

```

```{r}
#aha moment happend at the second 203 based on the video recording
#truncating the data to 60 seconds before and after the insight moment
## DH: ???
```

<!-- DH: At this point, it seems like you've skipped over most of Peng and Matsui's checklist and gone directly to drawing some plots? -->

```{r}
#plotting X and Y of right shoulder motion
## DH: long line
right_shoulder_plot <- ggplot(time.df2, aes(x = RIGHT_SHOULDER_X, y =  RIGHT_SHOULDER_Y)) +
    geom_point() +
    geom_path() +
    theme_classic()
right_shoulder_plot

```

<!-- DH: Anything notable here? -->

```{r}
#plotting shoulder's x axes over time

right_shoulder_x <- ggplot(time.df2, aes(x = X, y =  RIGHT_SHOULDER_X)) +
  geom_point() +
  geom_path() +
  geom_vline(xintercept = 203*30, linetype = "dashed", color = "red")+  
  
  xlab("time")+
  theme_classic()

right_shoulder_x


```

```{r}
#plotting shoulder's y axes over time

right_shoulder_y <- ggplot(time.df2, aes(x = X, y =  RIGHT_SHOULDER_Y)) +
  geom_point() +
  geom_path() +
  geom_vline(xintercept = 203*30, linetype = "dashed", color = "red") +
  xlab("time")+
  
  theme_classic()
right_shoulder_y


```

<!-- DH: Anything notable here? -->

# Principal Component Analysis 

```{r}
#preparing data for Priciple Component Analysis
## DH: unnecessary pipe; long line; unnecessary intermediate variable
shoulder.df = time.df2 %>% select(RIGHT_SHOULDER_X, RIGHT_SHOULDER_Y, RIGHT_SHOULDER_Z)
#shoulder.df
```
<!-- DH: Why is this two different cells? -->
```{r}
## DH: Using `T` rather than `TRUE` is not recommended
pca_shoulder = prcomp(shoulder.df, center = T, scale. = T)

summary(pca_shoulder)
```

<!-- DH: Anything notable here? -->

```{r}
#Extract principal components
pc_scores <- pca_shoulder$x  # Scores (coordinates of the data points in the new space)
pc_loadings <- pca_shoulder$rotation  # Loadings (coefficients of the original variables in the principal components)
```

```{r}
## DH: long line
#Visualizing the proportion of variance explained by each principal component
plot(cumsum(pca_shoulder$sdev^2) / sum(pca_shoulder$sdev^2), xlab = "Number of Principal Components", ylab = "Cumulative Proportion of Variance Explained", type = "b")

```


```{r}
#based on the plot above by two components 90% of the variance can be explained 
#Reduce dimensions
num_components_to_keep <- 2  # Choosing the number of components you want to keep
reduced_data <- pc_scores[, 1:num_components_to_keep]

# The 'reduced_data' dataframe now contains the data with reduced dimensions

```


```{r}
# Create a dataframe for the reduced data
reduced_data_df <- as.data.frame(reduced_data)

# Scatter plot of the reduced data
plot(reduced_data_df$PC1, reduced_data_df$PC2, 
     xlab = "Principal Component 1",
     ylab = "Principal Component 2",
     main = "Scatter Plot of Reduced Data")


```

<!-- DH: Anything notable here? -->

```{r}
#plotting a 3D plot of the data

plot_3D_shoulder <- plot_ly(
  data = shoulder.df,
  x = ~RIGHT_SHOULDER_X,
  y = ~RIGHT_SHOULDER_Y,
  z = ~RIGHT_SHOULDER_Z,
  #text = ~paste("Time: ", time),
  type = "scatter3d",
  mode = "markers"
)

# Customize the layout
layout <- list(
  scene = list(
    xaxis = list(title = 'X-axis'),
    yaxis = list(title = 'Y-axis'),
    zaxis = list(title = 'Z-axis')
  )
)

# Combine plot and layout
plot_3D_shoulder <- plot_3D_shoulder %>% layout(layout)

# Display the interactive plot
plot_3D_shoulder
```

<!-- DH: For me, a little hard to see with the points so large/opaque.  Anything notable here? -->

## Machine's confidnece in capturing the right motion

```{r}
#V stands for visibility of the body parts (the red line) and how confident the machine is in capturing the right motion.

TS_right_shoulder <- time.df2 %>%
    ggplot(aes(x= t_sec, y= RIGHT_SHOULDER_Y)) +
    geom_point() +
    geom_path() +
    geom_path(aes(y=RIGHT_SHOULDER_V), color="red") +
    geom_path(aes(y=RIGHT_WRIST_X), color="blue") +
    scale_x_continuous("time (sec.)", expand=c(0,0)) +
    theme_classic()
TS_right_shoulder

```

<!-- DH: Anything notable here? -->

